### ISSUE TITLE
Bundle example fails

### ISSUE THREAD

**Issue by gm112** [denoland/deno_emit#101]
Howdy. Just wanted to report that the [bundle example](https://github.com/denoland/deno_emit#bundle) bombs out when attempting to run. I'm not sure what the problem could be since the specific example doesn't do anything weird like use web workers, so I cannot give any valuable input beyond this report. To clarify, I did pass in `--allow-all` to the command line parameters for Deno, so I do not believe this to be a permission issue.

## Deno Version

```text
deno --version
deno 1.32.3 (release, x86_64-pc-windows-msvc)
v8 11.2.214.9
typescript 5.0.3
```

## Error Output

```text
Debugger listening on ws://127.0.0.1:9229/ws/2d09cf88-70c2-49a1-9057-29661fb93cd9
Visit chrome://inspect to connect to the debugger.
Deno is waiting for debugger to connect.
Debugger session started.
Debugger session ended
error: Uncaught (in promise) TypeError: WebAssembly.compile(): Argument 0 must be a buffer source
Process exited with code 1
```

**Comment by dsherret** [comment]
Let's track this in https://github.com/denoland/deno/issues/15015
