### ISSUE TITLE
import not working offline, requires wasm

### ISSUE THREAD

**Issue by marcusreese** [denoland/deno_emit#117]
Hi, is this a bug in your code or mine? It works fine for me with internet connection, but when I try re-running it offline, it fails. I used vsCode's quick fix to cache the import, but it still reaches out to the internet for the wasm file, and I tried caching that, but I wasn't able to do so.

From my file prepUiCode.ts:

```
import { transpile } from "https://deno.land/x/emit@0.22.0/mod.ts";

const singleUiEntryPoint = "tempGenerated/ui.loadAll.ts";
await Deno.writeTextFile(singleUiEntryPoint, loadLines.join("\n"));
const emittedFileUrlsAndContents = await transpile(singleUiEntryPoint); // line 352
```

Here's the failure message when running offline:

error: Uncaught (in promise) TypeError: error sending request for url (https://deno.land/x/emit@0.22.0/emit_bg.wasm): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known
      const wasmResponse = await fetch(wasm_url);
                           ^
    at eventLoopTick (ext:core/01_core.js:166:11)
    at async mainFetch (ext:deno_fetch/26_fetch.js:266:12)
    at async fetch (ext:deno_fetch/26_fetch.js:490:7)
    at async instantiateModule (https://deno.land/x/emit@0.22.0/emit.generated.js:491:28)
    at async https://deno.land/x/emit@0.22.0/emit.generated.js:444:27
    at async instantiate (https://deno.land/x/emit@0.22.0/emit.generated.js:422:11)
    at async transpile (https://deno.land/x/emit@0.22.0/mod.ts:229:38)
    at async _runDenoCompiler (file:///Users/marcusreese/Documents/mvp/_src/prepUiCode/prepUiCode.ts:352:38)

**Comment by marcusreese** [comment]
I see someone else had a similar issue: https://github.com/denoland/deno/issues/16521#issuecomment-1308189836 says, "it doesn't work offline" -- so I'm guessing there's no solution to my issue right now.

**Comment by ayame113** [comment]
Now that the [Cache API](https://deno.land/api@v1.33.2?s=Cache) and [Deno KV](https://deno.com/kv) have been implemented, wouldn't it be feasible to support offline wasm loading?
