### ISSUE TITLE
bundle: Prompts for write access to the deno cache, Deno.emit didn't

### ISSUE THREAD

**Issue by johnspurlock** [denoland/deno_emit#18]
`Deno.emit` worked just fine with `--allow-net --allow-read --allow-env`

On 1.22 with this new userland module:
```
 ️Deno requests write access to "${HOME}/Library/Caches/deno". Run again with --allow-write to bypass this prompt.
```

**Comment by kitsonk** [comment]
This is expected behaviour for a user land implementation to be able to write to the DENO_DIR.
