### ISSUE TITLE
emit: Does not support `bundle: 'module'`

### ISSUE THREAD

**Issue by johnspurlock** [denoland/deno_emit#19]
Deno.emit supported a bundle: 'module' mode, where the files returned returned `'deno:///bundle.js` with the bundled code.

Its confusing that `emit` is not a drop in replacement.  It looks like `bundle` is closer to this mode though, perhaps rename `emit` to avoid people thinking it supports the same contract?

**Comment by kitsonk** [comment]
Will handle under #29
