### ISSUE TITLE
docs: provide example of using a load function

### ISSUE THREAD

**Issue by KnorpelSenf** [denoland/deno_emit#23]
The old `Deno.emit` allowed us to pass the source code as a string by doing something like this:

```ts
await Deno.emit("/src.ts", {
  sources: { "/src.ts": sourceCode },
  compilerOptions: { target: "es6" },
});
```

This seems no longer possible.

The current workaround would be to write the source to a temporary file and to pass the file path, so that it is read in again.

**Comment by kitsonk** [comment]
The way to do it is to provide a `load()` function which provides the sources as you see fit in the options, versus supplying "sources".

We need to give an example of this though.

**Comment by KnorpelSenf** [comment]
I saw that there's a `load` option for `bundle` but it seems like it's not available for `emit`. Am I overlooking something here? 🤔

**Comment by kitsonk** [comment]
It needs to be fixed then, `emit()` should have a load function option.  The underlying code supports it in Rust, it is just the option isn't exposed.
