### ISSUE TITLE
bundle: compilerOptions `lib` property is missing

### ISSUE THREAD

**Issue by johnspurlock** [denoland/deno_emit#26]
Deno.emit had a property to pass libs used in the compilation

```ts
await Deno.emit(appPath, { bundle: 'module', compilerOptions: {
    lib: ['esnext', 'dom'],
} });
```

This new userland module does not have a similar property on its `CompilerOptions`.

**Comment by kitsonk** [comment]
deno_emit does not type check, making this option not useful
