### ISSUE TITLE
bundle: no longer typechecks by default, and cannot be enabled?

### ISSUE THREAD

**Issue by johnspurlock** [denoland/deno_emit#27]
Deno.emit used to typecheck modules by default when bundling.

The new `bundle` does not, any `TypeError`s occur only at runtime.

I'm not seeing an option for how to enable it, `checkJs: true` in `CompilerOptions` did not work

**Comment by kitsonk** [comment]
`deno_emit` does not do type checking...  The updated README explains this better.
