### ISSUE TITLE
Roadmap for inclusion of omitted APIs

### ISSUE THREAD

**Issue by jsejcksn** [denoland/deno_emit#6]
What's the roadmap for adding the other APIs which were [removed in Deno v`1.22.0`](https://deno.com/blog/v1.22#removal-of-unstable-denoemit-denoformatdiagnostics-and-denoapplysourcemap-apis)?

- Programmatic type-checking
- [`Deno.formatDiagnostics`](https://doc.deno.land/deno/unstable@v1.21.3/~/Deno.formatDiagnostics)
- [`Deno.applySourceMap`](https://doc.deno.land/deno/unstable@v1.21.3/~/Deno.applySourceMap)

It feels like an oversight that all of it was dropped from Deno, and only some of it was included here. While `emit` and `bundle` are certainly the core utilities, the above APIs were central to many of their use cases.

**Comment by dsherret** [comment]
Sorry, this is out of scope for deno_emit.
