### ISSUE TITLE
`emit` requires network access even when using a `load` function

### ISSUE THREAD

**Issue by not-my-profile** [denoland/deno_emit#81]
```ts
import { emit } from 'https://deno.land/x/emit/mod.ts';

let code = (await emit('', {load: async (_) => {
    return {kind: 'module', specifier: 'file:///_.ts', content: 'let x: number = 33'}
}}))['file:///_.ts'];

console.log(code);
```

If you save this code as `demo.ts` and run it, you get:

```
$ deno run --allow-read foo.ts 
⚠️  ┌ Deno requests network access to "deno.land".
   ├ Requested by `Deno.permissions.query()` API
   ├ Run again with --allow-net to bypass this prompt.
   └ Allow? [y/n] (y = yes, allow; n = no, deny)
```

**Comment by jollytoad** [comment]
Maybe related to this... https://github.com/denoland/deno_cache/issues/20

**Comment by Blocksnmore** [comment]
This request could also be from emit trying to download the wasm and caching it so that you can actually use the library

**Comment by dsherret** [comment]
> This request could also be from emit trying to download the wasm and caching it so that you can actually use the library

Yes, it's necessary to download the wasm file from deno.land/x. Follow https://github.com/denoland/deno/issues/2552 for how this could be improved.
